name: build and deploy

on:
  # which branch to deploy from
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - name: compile not-tetris
        run: |
          cd demos/not-tetris
          zig build
          mv ./zig-out/lib/not-tetris.wasm .
          cd -
      - name: set up pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: deploy website
        id: deployment
        uses: actions/deploy-pages@v1
